### ISSUE TITLE
Dijkstra not working

### ISSUE THREAD

**Issue by pradeepgangwar** [CodHeK/BaseCodes#1]
@CodHeK I used your Dijkstra code during my IDAA432C lab test. But to my surprise your code was not working. Please put authentic codes on GitHub next time no person like me should lose marks. 
cc - @sashank27

**Comment by sashank27** [comment]
Yes, we have been at a great loss because of the incorrect codes. @CodHeK work on fixing them asap.

**Comment by CodHeK** [comment]
Djikstra up and running @pradeepgangwar  @sashank27
